print("True and True =>", True and True)  
print("True and False =>", True and False)  
print("False and True =>", False and True)  
print("False and False =>", False and False)  
print("5 > 2 and -4 < 0 =>", 5 > 2 and -4 < 0)  
print("0 > 1 and 6 < 8 =>", 0 > 1 and 6 < 8)  