print("True or True =>", True or True)  
print("True or False =>", True or False)  
print("False or True =>", False or True)  
print("False or False =>", False or False)  
print("-4 > 2 or -7 < 0 =>", -4 > 2 or -7 < 0)  
print("4 > 6 or 9 < 4 =>", 4 > 6 or 9 < 4) 